version: 2

# Build documentation with MkDocs
mkdocs:
  configuration: mkdocs.yml

# Specify the build environment
build:
  os: ubuntu-22.04
  tools:
    python: "3.8"

# Optionally specify the Python version and additional dependencies
python:
  install:
    - requirements: docs/requirements.txt 