site_name: Curiosity.Utils
site_url: https://curiosityutils.readthedocs.io/en/latest/

nav:
  - Home: index.md

theme:
  name: material
  language: en
  font:
    text: Roboto
    code: Roboto Mono
  palette:
    primary: red
    accent: red
  features:
    - navigation.sections
    - navigation.expand

markdown_extensions:
  - codehilite
  - toc:
      permalink: true
  - markdown_include.include:
      base_path: docs
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - pymdownx.tabbed:
      alternate_style: true
  - admonition
  - def_list
  - attr_list

plugins:
  - search
  - git-revision-date-localized
  - minify
  - awesome-pages
  - static-i18n
  - git-authors
  - section-index
  - glightbox
  - redirects
  - exclude
  - macros
  - include-markdown 