site_name: Curiosity.Utils
site_url: https://curiosityutils.readthedocs.io/en/latest/

nav:
  - Home: index.md
  - Notifications:
    - Overview: Notiifications/index.md
    - Email Notifications: Notiifications/emails.md
    - SMS Notifications: Notiifications/sms.md

theme:
  name: material
  language: en
  logo: images/logo.png
  favicon: images/logo.png
  font:
    text: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, Cantarell, sans-serif
    code: 'JetBrains Mono', 'Fira Code', Monaco, 'Cascadia Code', 'Roboto Mono', Consolas, monospace
  palette:
    - scheme: default
      primary: blue
      accent: blue
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: blue
      accent: blue
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  
  features:
    - navigation.sections
    - navigation.expand
    - navigation.top
    - navigation.instant
    - navigation.tabs
    - navigation.tabs.sticky
    - search.highlight
    - search.share
    - search.suggest
    - content.code.copy
    - content.code.annotate
    - toc.follow
    - toc.integrate

extra_css:
  - stylesheets/extra.css

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/siisltd/Curiosity.Utils
    - icon: fontawesome/solid/globe
      link: https://siisltd.com

markdown_extensions:
  - codehilite
  - toc:
      permalink: true
  - markdown_include.include:
      base_path: docs
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - pymdownx.tabbed:
      alternate_style: true
  - admonition
  - def_list
  - attr_list
