<Project Sdk="Microsoft.NET.Sdk.Worker">

    <PropertyGroup>
        <TargetFrameworks>$(CuriosityTargetFrameworks)</TargetFrameworks>
        
        <PackageId>Curiosity.Hosting</PackageId>
        <Title>Curiosity.Hosting</Title>
        <Description>Hosting tools</Description>
        <Summary>Hosting tools</Summary>
        <PackageTags>Curiosity; Hosting; Boostrapping; siisltd</PackageTags>
        <Language>English</Language>
        
        <AssemblyVersion>1.0.0</AssemblyVersion>
        <FileVersion>1.0.0</FileVersion>
        <PackageVersion>2.0.0</PackageVersion>

        <Authors>Max Markelow (@markeli), Ilya Negrub (@ilya-negrub), Andrei Vinogradov (@anri-vin)</Authors>
        <Company>SIIS Ltd</Company>
        <Copyright>SIIS Ltd, 2026</Copyright>

        <PackageRequireLicenseAcceptance>false</PackageRequireLicenseAcceptance>
        <PackageLicenseExpression>MIT</PackageLicenseExpression>
        
        <PackageProjectUrl>https://github.com/siisltd/Curiosity.Utils</PackageProjectUrl>
        <RepositoryType>git</RepositoryType>
        <RepositoryUrl>https://github.com/siisltd/Curiosity.Utils</RepositoryUrl>
        <PackageReleaseNotes>https://github.com/siisltd/Curiosity.Utils/tree/master/src/Hosting/Curiosity.Hosting/CHANGELOG.md</PackageReleaseNotes>

        <OutputType>Library</OutputType>
        <Nullable>enable</Nullable>
        <IsPackable>true</IsPackable>
    </PropertyGroup>

    <PropertyGroup>
        <PackageIcon>siisltd.png</PackageIcon>
    </PropertyGroup>

    <ItemGroup>
        <None Include="..\..\..\siisltd.png" Pack="true" PackagePath="\" />
    </ItemGroup>
    
    <PropertyGroup Condition=" '$(Configuration)' == 'Release' ">
      <DocumentationFile>bin\Release\Curiosity.Hosting.xml</DocumentationFile>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="EntryPoint" />
        <PackageReference Include="MailKit" />
        <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" />
        <PackageReference Include="Microsoft.Extensions.Hosting" />
        <PackageReference Include="Microsoft.Extensions.Localization" />
        <PackageReference Include="Microsoft.Extensions.Localization.Abstractions" />
        <PackageReference Include="Microsoft.Extensions.Logging" />
        <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" />
        <PackageReference Include="NLog.Extensions.Logging" />
        <PackageReference Include="NLog.MailKit" />
        <PackageReference Include="System.ComponentModel.Annotations" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\..\Configuration\Curiosity.Configuration.YAML\Curiosity.Configuration.YAML.csproj" />
      <ProjectReference Include="..\..\Configuration\Curiosity.Configuration\Curiosity.Configuration.csproj" />
      <ProjectReference Include="..\..\Misc\Curiosity.Tools\Curiosity.Tools.csproj" />
    </ItemGroup>
</Project>
