name: Build and Test Utils

on:
  push:
    branches: [ $default-branch, master ]
  pull_request:
    branches: [ $default-branch, master ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-dotnet@v4
      with:
        dotnet-version: |
          9.0.x
          10.0.x
    - name: Restore tools
      run: dotnet tool restore
    - name: Clean
      run: dotnet cake --target=Clean --exclusive
    - name: Build
      run: dotnet cake --target=Build --exclusive

  tests:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: |
            9.0.x
            10.0.x
      - name: Restore tools
        run: dotnet tool restore
      - name: Clean
        run: dotnet cake --target=Clean --exclusive
      - name: Unit tests
        run: dotnet cake --target=UnitTests --exclusive
      - name: Integration tests
        run: dotnet cake --target=IntegrationTests --exclusive
