name: Publish packages to Nuget

on:
  push:
    branches: [ master ]

jobs:
  publish:

    runs-on: [self-hosted, linux]

    steps:
    - uses: actions/checkout@v4
    - name: Restore tools
      run: dotnet tool restore
    - name: Publish
      run: dotnet cake --target=GitHub --nugetApiKey=$nugetApiKey
      env:
        nugetApiKey: ${{ secrets.NUGETAPIKEY }}
