name: Publish packages to Nuget

on:
  push:
    branches: [ master ]

jobs:
  publish:

    runs-on: [self-hosted, linux]

    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-dotnet@v4
      env:
        DOTNET_INSTALL_DIR: ${{ runner.tool_cache }}/dotnet
      with:
        dotnet-version: |
          9.0.x
          10.0.x
    - name: Restore tools
      run: dotnet tool restore
    - name: Publish
      run: dotnet cake --target=GitHub --nugetApiKey=$nugetApiKey
      env:
        nugetApiKey: ${{ secrets.NUGETAPIKEY }}
